<?php

use Drupal\Core\Session\AccountInterface;

function my_helper_theme($existing, $type, $theme, $path) {
  return [
    'my_greeting_template' => [
      'variables' => [
        'user_name' => NULL,
        'user_count' => NULL,
        'greeting_text' => NULL,
        'visit_time' => NULL,
      ],
    ],
  ];
}

//This hook is triggered every time a user logs into the site

function my_helper_user_login(AccountInterface $account) {
  \Drupal::logger('my_helper')->notice('User @name has logged in', [
    '@name' => $account->getDisplayName(),
  ]);

  \Drupal::messenger()->addStatus(t('Welcome back, @name! Login tracked via Hook', [
    '@name' => $account->getDisplayName(),
  ]));
}
