<?php

declare (strict_types=1);

use Drupal\Core\Session\AccountInterface;

function my_helper_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'my_greeting_template' => [
      'variables' => [
        'user_name' => NULL,
        'user_count' => NULL,
        'greeting_text' => NULL,
        'visit_time' => NULL,
      ],
    ],
  ];
}

//This hook is triggered every time a user logs into the site

function my_helper_user_login(AccountInterface $account): void {
  \Drupal::service('my_helper.login_handler')->onUserLogin($account);
}
